sudo: false

language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_script:
    - composer install

script:
    - vendor/bin/phpcs --standard=psr2 src/
    - vendor/bin/phpmd src/ text phpmd.xml
    - vendor/bin/phpunit
